extends: airbnb
rules:
  react/jsx-filename-extension: 0
  react/destructuring-assignment: 0
  jsx-a11y/no-noninteractive-tabindex: 0
  jsx-a11y/no-noninteractive-element-interactions: 0
  jsx-a11y/no-static-element-interactions: 0
  react/jsx-no-bind: 0
  react/no-array-index-key: 0
